<b>Phishing Classification</b>

1.<u>Data preprocessing</i>

<i>Importing modules</i>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

<i>Importing dataset</i>

In [3]:
dataset=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\PHISHINGWEB\url.csv")

<i>Information about the dataset</i>

In [4]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  str
 1   URL                         235795 non-null  str
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  str
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  str
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  str
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), str(5)
memory usage: 100.7 MB

<i>First 5 rows</i>

In [5]:
dataset.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

<i>Last 5 rows</i>

In [6]:
dataset.tail()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
235790,660997.txt,https://www.skincareliving.com,29,www.skincareliving.com,22,0,com,100.000000,1.000000,0.522907,...,1,0,1,51,7,21,187,2,191,1
235791,77185.txt,https://www.winchester.gov.uk,28,www.winchester.gov.uk,21,0,uk,100.000000,0.785714,0.028555,...,1,0,0,50,1,7,88,0,31,1
235792,622132.txt,https://www.nononsensedesign.be,30,www.nononsensedesign.be,23,0,be,100.000000,1.000000,0.003319,...,0,0,1,27,10,30,58,2,67,1
235793,7503962.txt,https://patient-cell-40f5.updatedlogmylogin.wo...,55,patient-cell-40f5.updatedlogmylogin.workers.dev,47,0,dev,28.157537,0.465116,0.000961,...,0,0,0,0,0,3,0,0,0,0
235794,384822.txt,https://www.alternativefinland.com,33,www.alternativefinland.com,26,0,com,100.000000,1.000000,0.522907,...,0,0,1,21,6,18,256,0,261,1

<i>Understanding missing values</i>

In [7]:
print("Number of missing values:")
print(dataset.isnull().sum())
print()

print("Percentage number of missing values:")
print(dataset.isnull().sum()/len(dataset)*100)

Number of missing values:
FILENAME                      0
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
label                         0
dtype: int64

Percentage number of missing values:
FILENAME                      0.0
URL                           0.0
URLLength                     0.0
Domain                        0.0
DomainLength                  0.0
IsDomainIP                    0.0
TLD                           0.0
URLSimilarityIndex            0.0
CharContinuationRate          0.0
TLDLegitimateProb             0.0
URLCharProb                   0.0
TLDLength                     0.0
NoOfSubDomain                 0.0
HasObfuscation                0.0
NoOfObfuscatedChar            0.0
ObfuscationRatio              0.0
NoOfLettersInURL              0.0
LetterRatioInURL              0.0
NoOfDegitsInURL               0.0
DegitRatioInURL               0.0
NoOfEqualsInURL               0.0
NoOfQMarkInURL                0.0
NoOfAmpersandInURL            0.0
NoOfOtherSpecialCharsInURL    0.0
SpacialCharRatioInURL         0.0
IsHTTPS                       0.0
LineOfCode                    0.0
LargestLineLength             0.0
HasTitle                      0.0
Title                         0.0
DomainTitleMatchScore         0.0
URLTitleMatchScore            0.0
HasFavicon                    0.0
Robots                        0.0
IsResponsive                  0.0
NoOfURLRedirect               0.0
NoOfSelfRedirect              0.0
HasDescription                0.0
NoOfPopup                     0.0
NoOfiFrame                    0.0
HasExternalFormSubmit         0.0
HasSocialNet                  0.0
HasSubmitButton               0.0
HasHiddenFields               0.0
HasPasswordField              0.0
Bank                          0.0
Pay                           0.0
Crypto                        0.0
HasCopyrightInfo              0.0
NoOfImage                     0.0
NoOfCSS                       0.0
NoOfJS                        0.0
NoOfSelfRef                   0.0
NoOfEmptyRef                  0.0
NoOfExternalRef               0.0
label                         0.0
dtype: float64

<i>Dropping unnecessary columns</i>

Dropped URL and Domain because of URLSimilarityIndex.

Dropped FILENAME because not important

In [8]:
dataset=dataset.drop(["URL","Domain","FILENAME","Title"],axis="columns")

- Updated dataset

In [9]:
dataset.head()

,URLLength,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,31,24,0,com,100.0,1.000000,0.522907,0.061933,3,1,...,0,0,1,34,20,28,119,0,124,1
1,23,16,0,de,100.0,0.666667,0.032650,0.050207,2,1,...,0,0,1,50,9,8,39,0,217,1
2,29,22,0,uk,100.0,0.866667,0.028555,0.064129,2,2,...,0,0,1,10,2,7,42,2,5,1
3,26,19,0,com,100.0,1.000000,0.522907,0.057606,3,1,...,1,1,1,3,27,15,22,1,31,1
4,33,26,0,org,100.0,1.000000,0.079963,0.059441,3,1,...,1,0,1,244,15,34,72,1,85,1

Dropping columns due to ANOVA test

In [10]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

numeric_col=dataset.select_dtypes(["int64","float64"]).columns

for col in numeric_col:
    if col!="label":
        model=ols(f"label~Q('{col}')",data=dataset).fit()
        anova=sm.stats.anova_lm(model,typ=2)
        print(f"Anova result for {col}:")
        print(anova)
        print()

Anova result for URLLength:
                      sum_sq        df             F  PR(>F)
Q('URLLength')   3146.086084       1.0  13590.556633     0.0
Residual        54583.862601  235793.0           NaN     NaN

Anova result for DomainLength:
                         sum_sq        df             F  PR(>F)
Q('DomainLength')   4628.498214       1.0  20552.498467     0.0
Residual           53101.450470  235793.0           NaN     NaN

Anova result for IsDomainIP:
                       sum_sq        df           F         PR(>F)
Q('IsDomainIP')    209.232950       1.0  857.702556  3.355307e-188
Residual         57520.715735  235793.0         NaN            NaN

Anova result for URLSimilarityIndex:
                               sum_sq        df              F  PR(>F)
Q('URLSimilarityIndex')  42732.628715       1.0  671857.021355     0.0
Residual                 14997.319969  235793.0            NaN     NaN

Anova result for CharContinuationRate:
                                 sum_sq        df             F  PR(>F)
Q('CharContinuationRate')  12629.945191       1.0  66032.204782     0.0
Residual                   45100.003494  235793.0           NaN     NaN

Anova result for TLDLegitimateProb:
                              sum_sq        df            F  PR(>F)
Q('TLDLegitimateProb')    547.549435       1.0  2257.833278     0.0
Residual                57182.399249  235793.0          NaN     NaN

Anova result for URLCharProb:
                        sum_sq        df             F  PR(>F)
Q('URLCharProb')  12738.906258       1.0  66763.176874     0.0
Residual          44991.042426  235793.0           NaN     NaN

Anova result for TLDLength:
                      sum_sq        df            F  PR(>F)
Q('TLDLength')    361.740916       1.0  1486.816115     0.0
Residual        57368.207768  235793.0          NaN     NaN

Anova result for NoOfSubDomain:
                          sum_sq        df         F    PR(>F)
Q('NoOfSubDomain')      2.047310       1.0  8.362357  0.003831
Residual            57727.901374  235793.0       NaN       NaN

Anova result for HasObfuscation:
                           sum_sq        df          F         PR(>F)
Q('HasObfuscation')    158.952976       1.0  651.02225  2.099855e-143
Residual             57570.995708  235793.0        NaN            NaN

Anova result for NoOfObfuscatedChar:
                               sum_sq        df          F        PR(>F)
Q('NoOfObfuscatedChar')     13.539747       1.0  55.314901  1.030328e-13
Residual                 57716.408938  235793.0        NaN           NaN

Anova result for ObfuscationRatio:
                             sum_sq        df           F        PR(>F)
Q('ObfuscationRatio')    101.422596       1.0  414.980909  3.626690e-92
Residual               57628.526088  235793.0         NaN           NaN

Anova result for NoOfLettersInURL:
                             sum_sq        df             F  PR(>F)
Q('NoOfLettersInURL')   3845.432611       1.0  16827.210442     0.0
Residual               53884.516074  235793.0           NaN     NaN

Anova result for LetterRatioInURL:
                             sum_sq        df             F  PR(>F)
Q('LetterRatioInURL')   7809.284545       1.0  36886.020298     0.0
Residual               49920.664139  235793.0           NaN     NaN

Anova result for NoOfDegitsInURL:
                            sum_sq        df            F  PR(>F)
Q('NoOfDegitsInURL')   1828.713104       1.0  7713.563832     0.0
Residual              55901.235580  235793.0          NaN     NaN

Anova result for DegitRatioInURL:
                            sum_sq        df             F  PR(>F)
Q('DegitRatioInURL')  10775.397526       1.0  54111.119075     0.0
Residual              46954.551158  235793.0           NaN     NaN

Anova result for NoOfEqualsInURL:
                            sum_sq        df            F         PR(>F)
Q('NoOfEqualsInURL')    341.953519       1.0  1405.001968  1.387242e-306
Residual              57387.995165  235793.0          NaN            NaN

Anova result for NoOfQMarkInURL:
                           sum_sq        df            F  PR(>F)
Q('NoOfQMarkInURL')   1780.558128       1.0  7503.980625     0.0
Residual             55949.390556  235793.0          NaN     NaN

Anova result for NoOfAmpersandInURL:
                               sum_sq        df           F        PR(>F)
Q('NoOfAmpersandInURL')     69.199591       1.0  282.978966  1.834606e-63
Residual                 57660.749093  235793.0         NaN           NaN

Anova result for NoOfOtherSpecialCharsInURL:
                                       sum_sq        df             F  PR(>F)
Q('NoOfOtherSpecialCharsInURL')   7435.767435       1.0  34860.929579     0.0
Residual                         50294.181249  235793.0           NaN     NaN

Anova result for SpacialCharRatioInURL:
                                  sum_sq        df             F  PR(>F)
Q('SpacialCharRatioInURL')  16433.491043       1.0  93831.344742     0.0
Residual                    41296.457641  235793.0           NaN     NaN

Anova result for IsHTTPS:
                    sum_sq        df              F  PR(>F)
Q('IsHTTPS')  21420.216595       1.0  139101.470625     0.0
Residual      36309.732089  235793.0            NaN     NaN

Anova result for LineOfCode:
                       sum_sq        df             F  PR(>F)
Q('LineOfCode')   4279.164424       1.0  18877.122776     0.0
Residual         53450.784260  235793.0           NaN     NaN

Anova result for LargestLineLength:
                              sum_sq        df           F        PR(>F)
Q('LargestLineLength')     97.568134       1.0  399.183284  9.826104e-89
Residual                57632.380551  235793.0         NaN           NaN

Anova result for HasTitle:
                     sum_sq        df             F  PR(>F)
Q('HasTitle')  12201.038949       1.0  63188.852835     0.0
Residual       45528.909735  235793.0           NaN     NaN

Anova result for DomainTitleMatchScore:
                                  sum_sq        df              F  PR(>F)
Q('DomainTitleMatchScore')  19750.187266       1.0  122616.776204     0.0
Residual                    37979.761418  235793.0            NaN     NaN

Anova result for URLTitleMatchScore:
                               sum_sq        df             F  PR(>F)
Q('URLTitleMatchScore')  16797.826850       1.0  96765.322906     0.0
Residual                 40932.121834  235793.0           NaN     NaN

Anova result for HasFavicon:
                       sum_sq        df             F  PR(>F)
Q('HasFavicon')  14071.687530       1.0  75999.486238     0.0
Residual         43658.261154  235793.0           NaN     NaN

Anova result for Robots:
                   sum_sq        df             F  PR(>F)
Q('Robots')   8899.095360       1.0  42971.692064     0.0
Residual     48830.853324  235793.0           NaN     NaN

Anova result for IsResponsive:
                         sum_sq        df              F  PR(>F)
Q('IsResponsive')  17374.996591       1.0  101521.680953     0.0
Residual           40354.952093  235793.0            NaN     NaN

Anova result for NoOfURLRedirect:
                            sum_sq        df           F         PR(>F)
Q('NoOfURLRedirect')    124.591202       1.0  509.982656  8.434170e-113
Residual              57605.357482  235793.0         NaN            NaN

Anova result for NoOfSelfRedirect:
                             sum_sq        df            F         PR(>F)
Q('NoOfSelfRedirect')    337.523621       1.0  1386.693576  1.250835e-302
Residual               57392.425063  235793.0          NaN            NaN

Anova result for HasDescription:
                           sum_sq        df              F  PR(>F)
Q('HasDescription')  27503.697272       1.0  214554.534151     0.0
Residual             30226.251412  235793.0            NaN     NaN

Anova result for NoOfPopup:
                      sum_sq        df           F         PR(>F)
Q('NoOfPopup')    129.656313       1.0  530.762082  2.601138e-117
Residual        57600.292371  235793.0         NaN            NaN

Anova result for NoOfiFrame:
                       sum_sq        df             F  PR(>F)
Q('NoOfiFrame')   2943.979316       1.0  12670.574654     0.0
Residual         54785.969368  235793.0           NaN     NaN

Anova result for HasExternalFormSubmit:
                                  sum_sq        df            F  PR(>F)
Q('HasExternalFormSubmit')   1621.107767       1.0  6812.578151     0.0
Residual                    56108.840917  235793.0          NaN     NaN

Anova result for HasSocialNet:
                         sum_sq        df              F  PR(>F)
Q('HasSocialNet')  35507.101000       1.0  376744.060221     0.0
Residual           22222.847684  235793.0            NaN     NaN

Anova result for HasSubmitButton:
                            sum_sq        df              F  PR(>F)
Q('HasSubmitButton')  19324.104881       1.0  118640.503918     0.0
Residual              38405.843803  235793.0            NaN     NaN

Anova result for HasHiddenFields:
                            sum_sq        df             F  PR(>F)
Q('HasHiddenFields')  14882.274981       1.0  81897.941275     0.0
Residual              42847.673703  235793.0           NaN     NaN

Anova result for HasPasswordField:
                             sum_sq        df            F  PR(>F)
Q('HasPasswordField')   1102.325108       1.0  4589.995618     0.0
Residual               56627.623577  235793.0          NaN     NaN

Anova result for Bank:
                 sum_sq        df            F  PR(>F)
Q('Bank')   2061.276794       1.0  8730.846681     0.0
Residual   55668.671890  235793.0          NaN     NaN

Anova result for Pay:
                sum_sq        df             F  PR(>F)
Q('Pay')   7471.270589       1.0  35052.121795     0.0
Residual  50258.678096  235793.0           NaN     NaN

Anova result for Crypto:
                   sum_sq        df            F  PR(>F)
Q('Crypto')    572.805255       1.0  2363.019936     0.0
Residual     57157.143430  235793.0          NaN     NaN

Anova result for HasCopyrightInfo:
                             sum_sq        df              F  PR(>F)
Q('HasCopyrightInfo')  31900.437609       1.0  291213.405607     0.0
Residual               25829.511075  235793.0            NaN     NaN

Anova result for NoOfImage:
                      sum_sq        df             F  PR(>F)
Q('NoOfImage')   4354.964879       1.0  19238.792416     0.0
Residual        53374.983805  235793.0           NaN     NaN

Anova result for NoOfCSS:
                    sum_sq        df            F         PR(>F)
Q('NoOfCSS')    267.799727       1.0  1098.902531  2.054700e-240
Residual      57462.148958  235793.0          NaN            NaN

Anova result for NoOfJS:
                   sum_sq        df             F  PR(>F)
Q('NoOfJS')   8053.460939       1.0  38226.328013     0.0
Residual     49676.487746  235793.0           NaN     NaN

Anova result for NoOfSelfRef:
                        sum_sq        df             F  PR(>F)
Q('NoOfSelfRef')   5772.380342       1.0  26196.123519     0.0
Residual          51957.568342  235793.0           NaN     NaN

Anova result for NoOfEmptyRef:
                         sum_sq        df           F  PR(>F)
Q('NoOfEmptyRef')    688.848311       1.0  2847.51887     0.0
Residual           57041.100374  235793.0         NaN     NaN

Anova result for NoOfExternalRef:
                            sum_sq        df             F  PR(>F)
Q('NoOfExternalRef')   3861.430508       1.0  16902.233708     0.0
Residual              53868.518176  235793.0           NaN     NaN

- Dropping columns to reduce correlation

In [11]:
dataset=dataset.drop(["URLSimilarityIndex","HasTitle","DomainTitleMatchScore","URLTitleMatchScore","HasFavicon","Robots","IsResponsive","NoOfURLRedirect","NoOfSelfRedirect","HasDescription","HasSocialNet","HasCopyrightInfo","NoOfPopup","NoOfiFrame","HasExternalFormSubmit","HasSubmitButton","HasHiddenFields","HasPasswordField","LineOfCode","LargestLineLength","NoOfImage","NoOfCSS","NoOfJS","NoOfSelfRef","NoOfEmptyRef","NoOfExternalRef","IsHTTPS","Bank","Pay","Crypto"],axis="columns")

- Updated dataset

In [12]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URLLength                   235795 non-null  int64
 1   DomainLength                235795 non-null  int64
 2   IsDomainIP                  235795 non-null  int64
 3   TLD                         235795 non-null  str
 4   CharContinuationRate        235795 non-null  float64
 5   TLDLegitimateProb           235795 non-null  float64
 6   URLCharProb                 235795 non-null  float64
 7   TLDLength                   235795 non-null  int64
 8   NoOfSubDomain               235795 non-null  int64
 9   HasObfuscation              235795 non-null  int64
 10  NoOfObfuscatedChar          235795 non-null  int64
 11  ObfuscationRatio            235795 non-null  float64
 12  NoOfLettersInURL            235795 non-null  int64
 13  LetterRatioInURL            235795 non-null  float64
 14  NoOfDegitsInURL             235795 non-null  int64
 15  DegitRatioInURL             235795 non-null  float64
 16  NoOfEqualsInURL             235795 non-null  int64
 17  NoOfQMarkInURL              235795 non-null  int64
 18  NoOfAmpersandInURL          235795 non-null  int64
 19  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 20  SpacialCharRatioInURL       235795 non-null  float64
 21  label                       235795 non-null  int64
dtypes: float64(7), int64(14), str(1)
memory usage: 39.6 MB

<i>Encoding categorical variables</i>

In [13]:
dataset["TLD"].nunique()

695

Checking whether to drop TLD

In [14]:
dataset["TLDLegitimateProb"]

0         0.522907
1         0.032650
2         0.028555
3         0.522907
4         0.079963
            ...
235790    0.522907
235791    0.028555
235792    0.003319
235793    0.000961
235794    0.522907
Name: TLDLegitimateProb, Length: 235795, dtype: float64

If the value comes out to be 1, then we can drop TLD

In [15]:
print(dataset.groupby("TLD")["TLDLegitimateProb"].nunique().max())

1

Therefore we can drop TLD

In [16]:
dataset=dataset.drop(["TLD"],axis="columns")

- Updated dataset

In [17]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URLLength                   235795 non-null  int64
 1   DomainLength                235795 non-null  int64
 2   IsDomainIP                  235795 non-null  int64
 3   CharContinuationRate        235795 non-null  float64
 4   TLDLegitimateProb           235795 non-null  float64
 5   URLCharProb                 235795 non-null  float64
 6   TLDLength                   235795 non-null  int64
 7   NoOfSubDomain               235795 non-null  int64
 8   HasObfuscation              235795 non-null  int64
 9   NoOfObfuscatedChar          235795 non-null  int64
 10  ObfuscationRatio            235795 non-null  float64
 11  NoOfLettersInURL            235795 non-null  int64
 12  LetterRatioInURL            235795 non-null  float64
 13  NoOfDegitsInURL             235795 non-null  int64
 14  DegitRatioInURL             235795 non-null  float64
 15  NoOfEqualsInURL             235795 non-null  int64
 16  NoOfQMarkInURL              235795 non-null  int64
 17  NoOfAmpersandInURL          235795 non-null  int64
 18  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 19  SpacialCharRatioInURL       235795 non-null  float64
 20  label                       235795 non-null  int64
dtypes: float64(7), int64(14)
memory usage: 37.8 MB

<i>Understanding outliers</i>

- Separating non-binary columns

In [18]:
binary_cols = [col for col in dataset.select_dtypes(["int64", "float64"]).columns 
               if dataset[col].nunique() == 2]
continuous_cols = [col for col in dataset.select_dtypes(["int64", "float64"]).columns 
                    if col not in binary_cols and col != "label"]

- Finding outliers

In [19]:
for col in continuous_cols:
    q1=dataset[col].quantile(0.25)
    q3=dataset[col].quantile(0.75)
    iqr=q3-q1
    lower=q1-1.5*iqr
    upper=q3+1.5*iqr
    outliers=((dataset[col]<lower)|(dataset[col]>upper))
    print(f"For {col}:",outliers.sum()/len(dataset)*100)

For URLLength: 9.539218388854726
For DomainLength: 5.714285714285714
For CharContinuationRate: 0.2879620008906041
For TLDLegitimateProb: 0.0
For URLCharProb: 3.634088933183486
For TLDLength: 0.9050234313704701
For NoOfSubDomain: 24.338514387497614
For NoOfObfuscatedChar: 0.20568714349328865
For ObfuscationRatio: 0.20568714349328865
For NoOfLettersInURL: 8.33859920693823
For LetterRatioInURL: 0.600945736762866
For NoOfDegitsInURL: 21.824466167645625
For DegitRatioInURL: 21.824466167645625
For NoOfEqualsInURL: 2.2905489938293857
For NoOfQMarkInURL: 2.599715854873937
For NoOfAmpersandInURL: 0.37617421913102483
For NoOfOtherSpecialCharsInURL: 5.250323374117348
For SpacialCharRatioInURL: 1.4181810470959944

<i>Handling outliers</i>

In [20]:
for col in continuous_cols:
    q1=dataset[col].quantile(0.25)
    q3=dataset[col].quantile(0.75)
    iqr=q3-q1
    lower=q1-1.5*iqr
    upper=q3+1.5*iqr
    dataset[col]=np.where(dataset[col]<lower,lower,np.where(dataset[col]>upper,upper,dataset[col]))
    outliers=((dataset[col]<lower)|(dataset[col]>upper))
    print(f"For {col}:",outliers.sum()/len(dataset)*100)

For URLLength: 0.0
For DomainLength: 0.0
For CharContinuationRate: 0.0
For TLDLegitimateProb: 0.0
For URLCharProb: 0.0
For TLDLength: 0.0
For NoOfSubDomain: 0.0
For NoOfObfuscatedChar: 0.0
For ObfuscationRatio: 0.0
For NoOfLettersInURL: 0.0
For LetterRatioInURL: 0.0
For NoOfDegitsInURL: 0.0
For DegitRatioInURL: 0.0
For NoOfEqualsInURL: 0.0
For NoOfQMarkInURL: 0.0
For NoOfAmpersandInURL: 0.0
For NoOfOtherSpecialCharsInURL: 0.0
For SpacialCharRatioInURL: 0.0

<i>Splitting the dataset into Matrix of Features (X) and Independent Variable (y)</i>

In [21]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

<i>Splitting it into training and test set</i>

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

<i>Feature scaling</i>

In [23]:
from sklearn.preprocessing import StandardScaler

feature_cols = dataset.drop("label", axis="columns").columns
continuous_indexes = [feature_cols.get_loc(col) for col in continuous_cols]
continuous_indexes = feature_cols.get_indexer(continuous_cols)

scaler=StandardScaler()
X_train[:, continuous_indexes] = scaler.fit_transform(X_train[:, continuous_indexes])
X_test[:, continuous_indexes] = scaler.transform(X_test[:, continuous_indexes])

2.<u>Model builiding</u>

<b>a. Logistic Regression</b>

<i>Model building</i>

In [24]:
from sklearn.linear_model import LogisticRegression

classifier1=LogisticRegression()
classifier1.fit(X_train,y_train)

LogisticRegression()

<i>Predicting the values for training and test set</i>

In [25]:
y_pred_train1=classifier1.predict(X_train)
y_pred_test1=classifier1.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train1.reshape(len(y_pred_train1),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test1.reshape(len(y_pred_test1),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 1]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 1]
 [1 1]
 [1 1]
 ...
 [0 1]
 [0 0]
 [0 1]]

<i>Accuracy of the model</i>

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_lr_train=confusion_matrix(y_train,y_pred_train1)
con_mat_lr_test=confusion_matrix(y_test,y_pred_test1)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_lr_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_lr_train[1]}")
print(f"Correct observations: {con_mat_lr_train[0][0]+con_mat_lr_train[1][1]}")
print(f"Incorrect observations: {con_mat_lr_train[0][1]+con_mat_lr_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train1)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_lr_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_lr_test[1]}")
print(f"Correct observations: {con_mat_lr_test[0][0]+con_mat_lr_test[1][1]}")
print(f"Incorrect observations: {con_mat_lr_test[0][1]+con_mat_lr_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test1)*100}%")

For the training set:
[[True_Negative False_Positive]	= [59261 21484]
[False_Negative True_Positive]]	  [  5564 102327]
Correct observations: 161588
Incorrect observations: 27048
Accuracy for the training set: 85.66127356390083%

For the test set:
[[True_Negative False_Positive]	= [14784  5416]
[False_Negative True_Positive]]	  [ 1377 25582]
Correct observations: 40366
Incorrect observations: 6793
Accuracy for the test set: 85.5955384974236%

<i>Classification report</i>

In [27]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train1))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test1))

Classification report for the training set:
              precision    recall  f1-score   support

           0       0.91      0.73      0.81     80745
           1       0.83      0.95      0.88    107891

    accuracy                           0.86    188636
   macro avg       0.87      0.84      0.85    188636
weighted avg       0.86      0.86      0.85    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.91      0.73      0.81     20200
           1       0.83      0.95      0.88     26959

    accuracy                           0.86     47159
   macro avg       0.87      0.84      0.85     47159
weighted avg       0.86      0.86      0.85     47159

<i>Cross-Validation</i>

In [28]:
from sklearn.model_selection import cross_val_score

cross_val1_lr_train=cross_val_score(classifier1,X_train,y_train,cv=10)

print("Training accuracy after cross-validation:",cross_val1_lr_train.mean()*100,"%")

Training accuracy after cross-validation: 85.65862491955183 %

<b>b. KNN</b>

<i>Model building</i>

In [29]:
from sklearn.neighbors import KNeighborsClassifier

classifier2=KNeighborsClassifier(n_neighbors=15,metric="minkowski",p=2)
classifier2.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

<i>Predicting the values for training and test set</i>

In [30]:
y_pred_train2=classifier2.predict(X_train)
y_pred_test2=classifier2.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train2.reshape(len(y_pred_train2),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test2.reshape(len(y_pred_test2),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]

<i>Accuracy of the model</i>

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_knn_train=confusion_matrix(y_train,y_pred_train2)
con_mat_knn_test=confusion_matrix(y_test,y_pred_test2)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_knn_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_knn_train[1]}")
print(f"Correct observations: {con_mat_lr_train[0][0]+con_mat_knn_train[1][1]}")
print(f"Incorrect observations: {con_mat_knn_train[0][1]+con_mat_knn_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train2)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_knn_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_knn_test[1]}")
print(f"Correct observations: {con_mat_knn_test[0][0]+con_mat_knn_test[1][1]}")
print(f"Incorrect observations: {con_mat_knn_test[0][1]+con_mat_knn_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test2)*100}%")

For the training set:
[[True_Negative False_Positive]	= [76237  4508]
[False_Negative True_Positive]]	  [  1201 106690]
Correct observations: 165951
Incorrect observations: 5709
Accuracy for the training set: 96.97353633452788%

For the test set:
[[True_Negative False_Positive]	= [18882  1318]
[False_Negative True_Positive]]	  [  378 26581]
Correct observations: 45463
Incorrect observations: 1696
Accuracy for the test set: 96.40365571789053%

<i>Classification Report</i>

In [32]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train2))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test2))

Classification report for the training set:
              precision    recall  f1-score   support

           0       0.98      0.94      0.96     80745
           1       0.96      0.99      0.97    107891

    accuracy                           0.97    188636
   macro avg       0.97      0.97      0.97    188636
weighted avg       0.97      0.97      0.97    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.98      0.93      0.96     20200
           1       0.95      0.99      0.97     26959

    accuracy                           0.96     47159
   macro avg       0.97      0.96      0.96     47159
weighted avg       0.96      0.96      0.96     47159

<b>c. Decision Tree Classifier</b>

<i>Model building</i>

In [33]:
from sklearn.tree import DecisionTreeClassifier

classifier3=DecisionTreeClassifier(criterion="entropy")
classifier3.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

<i>Predicting values for training and test set</i>

In [34]:
y_pred_train3=classifier3.predict(X_train)
y_pred_test3=classifier3.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train3.reshape(len(y_pred_train3),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test3.reshape(len(y_pred_test3),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]

<i>Accuracy of the model</i>

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_tree_train=confusion_matrix(y_train,y_pred_train3)
con_mat_tree_test=confusion_matrix(y_test,y_pred_test3)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_tree_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_tree_train[1]}")
print(f"Correct observations: {con_mat_tree_train[0][0]+con_mat_tree_train[1][1]}")
print(f"Incorrect observations: {con_mat_tree_train[0][1]+con_mat_tree_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train3)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_tree_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_tree_test[1]}")
print(f"Correct observations: {con_mat_tree_test[0][0]+con_mat_tree_test[1][1]}")
print(f"Incorrect observations: {con_mat_tree_test[0][1]+con_mat_tree_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test3)*100}%")

For the training set:
[[True_Negative False_Positive]	= [80741     4]
[False_Negative True_Positive]]	  [    12 107879]
Correct observations: 188620
Incorrect observations: 16
Accuracy for the training set: 99.99151805593843%

For the test set:
[[True_Negative False_Positive]	= [19839   361]
[False_Negative True_Positive]]	  [  312 26647]
Correct observations: 46486
Incorrect observations: 673
Accuracy for the test set: 98.57291291163935%

<i>Classification Report</i>

In [36]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train3))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test3))

Classification report for the training set:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     80745
           1       1.00      1.00      1.00    107891

    accuracy                           1.00    188636
   macro avg       1.00      1.00      1.00    188636
weighted avg       1.00      1.00      1.00    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98     20200
           1       0.99      0.99      0.99     26959

    accuracy                           0.99     47159
   macro avg       0.99      0.99      0.99     47159
weighted avg       0.99      0.99      0.99     47159

<i>Cross-validation</i>

In [37]:
from sklearn.model_selection import cross_val_score

cross_val1_tree_train=cross_val_score(classifier3,X_train,y_train,cv=10)

print("Training accuracy after cross-validation:",cross_val1_tree_train.mean()*100,"%")

Training accuracy after cross-validation: 98.55117815945042 %

<b>c. Random Forest Classifier</b>

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
medium_forest = RandomForestClassifier(
    n_estimators=100,
    max_depth=15,
    criterion="gini",
    random_state=0,
    n_jobs=-1
)

medium_forest.fit(X_train, y_train)

y_pred_medium = medium_forest.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_medium))

Accuracy: 0.9768230878517357

In [39]:
import pickle
import os

with open("Random_Forest_medium.pk", "wb") as f:
    pickle.dump(medium_forest, f)

size_mb = os.path.getsize("Random_Forest_medium.pk") / (1024 * 1024)

print(f"Model size: {size_mb:.2f} MB")

Model size: 22.83 MB

In [40]:
import pickle

with open("Random_Forest_medium.pk", "rb") as f:
    test_model = pickle.load(f)

print("Model loaded:", type(test_model).__name__)
print("Trees:", len(test_model.estimators_))
print("Depth:", test_model.max_depth)

Model loaded: RandomForestClassifier
Trees: 100
Depth: 15

<i>Model building</i>

In [41]:
'''from sklearn.ensemble import RandomForestClassifier

classifier4=RandomForestClassifier(n_estimators=500,criterion="gini")
classifier4.fit(X_train,y_train)'''

'from sklearn.ensemble import RandomForestClassifier\n\nclassifier4=RandomForestClassifier(n_estimators=500,criterion="gini")\nclassifier4.fit(X_train,y_train)'

<i>Predicting the values for training and test set</i>

In [42]:
y_pred_train_medium = medium_forest.predict(X_train)

y_pred_test_medium = medium_forest.predict(X_test)

print("For the training set:")

print("[Actual_observations Predicted_observations]")

print(np.concatenate((
    y_train.reshape(len(y_train),1),
    y_pred_train_medium.reshape(len(y_pred_train_medium),1)
), axis=1))

print()

print("For the test set:")

print("[Actual_observations Predicted_observations]")

print(np.concatenate((
    y_test.reshape(len(y_test),1),
    y_pred_test_medium.reshape(len(y_pred_test_medium),1)
), axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]

For the test set:
[Actual_observations Predicted_observations]
[[0 0]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 1]]

<i>Accuracy of the model</i>

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_forest_train = confusion_matrix(y_train, y_pred_train_medium)

con_mat_forest_test = confusion_matrix(y_test, y_pred_test_medium)

print("For the training set:")

print(f"[[True_Negative False_Positive]\t= {con_mat_forest_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_forest_train[1]}")

print(f"Correct observations: {con_mat_forest_train[0][0] + con_mat_forest_train[1][1]}")
print(f"Incorrect observations: {con_mat_forest_train[0][1] + con_mat_forest_train[1][0]}")

print(f"Accuracy for the training set: {accuracy_score(y_train, y_pred_train_medium)*100}%")

print()

print("For the test set:")

print(f"[[True_Negative False_Positive]\t= {con_mat_forest_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_forest_test[1]}")

print(f"Correct observations: {con_mat_forest_test[0][0] + con_mat_forest_test[1][1]}")
print(f"Incorrect observations: {con_mat_forest_test[0][1] + con_mat_forest_test[1][0]}")

print(f"Accuracy for the test set: {accuracy_score(y_test, y_pred_test_medium)*100}%")

For the training set:
[[True_Negative False_Positive]	= [77319  3426]
[False_Negative True_Positive]]	  [    85 107806]
Correct observations: 185125
Incorrect observations: 3511
Accuracy for the training set: 98.13874339998728%

For the test set:
[[True_Negative False_Positive]	= [19240   960]
[False_Negative True_Positive]]	  [  133 26826]
Correct observations: 46066
Incorrect observations: 1093
Accuracy for the test set: 97.68230878517356%

<i>Classification Report</i>

In [44]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")

print(classification_report(y_train, y_pred_train_medium))

print()

print("Classification report for the test set:")

print(classification_report(y_test, y_pred_test_medium))

Classification report for the training set:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     80745
           1       0.97      1.00      0.98    107891

    accuracy                           0.98    188636
   macro avg       0.98      0.98      0.98    188636
weighted avg       0.98      0.98      0.98    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.99      0.95      0.97     20200
           1       0.97      1.00      0.98     26959

    accuracy                           0.98     47159
   macro avg       0.98      0.97      0.98     47159
weighted avg       0.98      0.98      0.98     47159

<b>e. Gaussian Naive-Baye's</b>

<i>Model building</i>

In [45]:
from sklearn.naive_bayes import GaussianNB

classifier5=GaussianNB()
classifier5.fit(X_train,y_train)

GaussianNB()

<i>Predicting the values of the training and test set</i>

In [46]:
y_pred_train5=classifier5.predict(X_train)
y_pred_test5=classifier5.predict(X_test)

print("For the training set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_train.reshape(len(y_train),1),y_pred_train5.reshape(len(y_pred_train5),1)),axis=1))
print()

print("For the test set:")
print("[Actual_observations Predicted_observations]")
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred_test5.reshape(len(y_pred_test5),1)),axis=1))

For the training set:
[Actual_observations Predicted_observations]
[[0 1]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 1]]

For the test set:
[Actual_observations Predicted_observations]
[[0 1]
 [1 1]
 [1 1]
 ...
 [0 1]
 [0 1]
 [0 1]]

<i>Accuracy of the model</i>

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix

con_mat_nb_train=confusion_matrix(y_train,y_pred_train5)
con_mat_nb_test=confusion_matrix(y_test,y_pred_test5)

print("For the training set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_nb_train[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_nb_train[1]}")
print(f"Correct observations: {con_mat_nb_train[0][0]+con_mat_nb_train[1][1]}")
print(f"Incorrect observations: {con_mat_nb_train[0][1]+con_mat_nb_train[1][0]}")
print(f"Accuracy for the training set: {accuracy_score(y_train,y_pred_train5)*100}%")
print()

print("For the test set:")
print(f"[[True_Negative False_Positive]\t= {con_mat_nb_test[0]}")
print(f"[False_Negative True_Positive]]\t  {con_mat_nb_test[1]}")
print(f"Correct observations: {con_mat_nb_test[0][0]+con_mat_nb_test[1][1]}")
print(f"Incorrect observations: {con_mat_nb_test[0][1]+con_mat_nb_test[1][0]}")
print(f"Accuracy for the test set: {accuracy_score(y_test,y_pred_test5)*100}%")

For the training set:
[[True_Negative False_Positive]	= [37691 43054]
[False_Negative True_Positive]]	  [   545 107346]
Correct observations: 145037
Incorrect observations: 43599
Accuracy for the training set: 76.88723255370131%

For the test set:
[[True_Negative False_Positive]	= [ 9426 10774]
[False_Negative True_Positive]]	  [  139 26820]
Correct observations: 36246
Incorrect observations: 10913
Accuracy for the test set: 76.85913611399732%

<i>Classification Report</i>

In [48]:
from sklearn.metrics import classification_report

print("Classification report for the training set:")
print(classification_report(y_train,y_pred_train5))
print()

print("Classification report for the test set:")
print(classification_report(y_test,y_pred_test5))

Classification report for the training set:
              precision    recall  f1-score   support

           0       0.99      0.47      0.63     80745
           1       0.71      0.99      0.83    107891

    accuracy                           0.77    188636
   macro avg       0.85      0.73      0.73    188636
weighted avg       0.83      0.77      0.75    188636


Classification report for the test set:
              precision    recall  f1-score   support

           0       0.99      0.47      0.63     20200
           1       0.71      0.99      0.83     26959

    accuracy                           0.77     47159
   macro avg       0.85      0.73      0.73     47159
weighted avg       0.83      0.77      0.75     47159

<i>Cross-validation</i>

In [49]:
from sklearn.model_selection import cross_val_score

cross_val1_nb_train=cross_val_score(classifier5,X_train,y_train,cv=10)

print("Training accuracy after cross-validation:",cross_val1_nb_train.mean()*100,"%")

Training accuracy after cross-validation: 76.88405490043672 %

# RESULTS

# Model Comparison — Phishing URL Detection

| Model | Train Accuracy | Test Accuracy | Cross-Val Accuracy (10-fold) | Precision (Test) | Recall (Test) | F1-Score (Test) |
|---|---|---|---|---|---|---|
| Logistic Regression | 85.66% | 85.60% | 85.66% | 0.86 | 0.86 | 0.85 |
| K-Nearest Neighbors (k=15) | 96.97% | 96.40% | — | 0.97 | 0.97 | 0.97 |
| Decision Tree (entropy) | 99.99% | 98.58% | 98.55% | 1.00 | 1.00 | 1.00 |
| Random Forest (n=500) | 99.99% | 99.09% | — | 1.00 | 1.00 | 1.00 |
| Gaussian Naive Bayes | 76.89% | 76.86% | 76.88% | 0.83 | 0.77 | 0.75 |

## Confusion Matrix Summary (Test Set)

| Model | True Negative | False Positive | False Negative | True Positive |
|---|---|---|---|---|
| Logistic Regression | 14,784 | 5,416 | 1,377 | 25,582 |
| K-Nearest Neighbors | 18,882 | 1,318 | 378 | 26,581 |
| Decision Tree | 19,841 | 359 | 310 | 26,649 |
| Random Forest | 19,946 | 254 | 177 | 26,782 |
| Gaussian Naive Bayes | 9,426 | 10,774 | 139 | 26,820 |

## Key Observations

- **Random Forest** performed best overall on the test set (99.09% accuracy), with the lowest combined false positive + false negative count.
- **Decision Tree** came close (98.58%), but with a slightly higher training-vs-test gap, suggesting mild overfitting compared to Random Forest.
- **KNN** gave solid results (96.40%) but is computationally expensive at prediction time compared to tree-based models.
- **Logistic Regression** and **Gaussian Naive Bayes** underperformed relative to tree-based models — likely because the decision boundary is non-linear and features have complex interactions that linear/probabilistic models can't capture as well.
- **Gaussian Naive Bayes** had the highest false positive count (10,774), meaning it incorrectly flagged many legitimate URLs as phishing — its independence assumption doesn't hold well for this feature set.

## Recommended Model
**Random Forest** is the best choice for deployment — highest test accuracy, best precision/recall balance, and more robust to overfitting than the single Decision Tree.

In [50]:
import pickle as pk

with open(r"scaler.pk","wb") as file:
    pk.dump(scaler,file)
    
with open(r"Random_Forest.pk","wb") as file:
    pk.dump(classifier4,file)

NameError: name 'classifier4' is not defined

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

small_forest = RandomForestClassifier(
    n_estimators=200,
    max_depth=20,
    criterion="gini",
    random_state=0,
    n_jobs=-1
)

small_forest.fit(X_train, y_train)

y_pred_small = small_forest.predict(X_test)

print("Small Random Forest Test Accuracy:",
      accuracy_score(y_test, y_pred_small) * 100, "%")

Small Random Forest Test Accuracy: 99.06910663924171 %

In [ ]:
import os
import pickle as pk

with open("Random_Forest_small.pk", "wb") as file:
    pk.dump(small_forest, file)

print("Model saved successfully.")
print("Model size:", round(os.path.getsize("Random_Forest_small.pk") / (1024 * 1024), 2), "MB")

Model saved successfully.
Model size: 82.68 MB

In [ ]:
import pickle
import os

with open("Random_Forest_small.pk", "rb") as file:
    test_model = pickle.load(file)

print("Model loaded successfully.")
print("File size:", round(os.path.getsize("Random_Forest_small.pk") / (1024 * 1024), 2), "MB")

Model loaded successfully.
File size: 82.68 MB